[package]
name = "puck_registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "puck: Packagist / registry client with VCR replay and live p2 fetch"

[dependencies]
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
puck_version.workspace = true
puck_dist.workspace = true
reqwest.workspace = true

[dev-dependencies]
tempfile.workspace = true
