//! Native port of `phpstan/extension-installer` `Plugin::process`.
//!
//! Upstream: phpstan/extension-installer @ 1.4.3 (`src/Plugin.php`).
//! Writes `vendor/phpstan/extension-installer/src/GeneratedConfig.php`.

use crate::{Error, Result};
use serde_json::Value;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_REL: &str = "vendor/phpstan/extension-installer/src/GeneratedConfig.php";

const SKIP_NOT_INSTALLED: &[&str] = &[
    "phpstan/phpstan",
    "phpstan/phpstan-shim",
    "phpstan/phpdoc-parser",
    "phpstan/extension-installer",
];

const GENERATED_TEMPLATE: &str = r#"<?php declare(strict_types = 1);

namespace PHPStan\ExtensionInstaller;

/**
 * This class is generated by phpstan/extension-installer.
 * @internal
 */
final class GeneratedConfig
{

	public const EXTENSIONS = %EXTENSIONS%;

	public const NOT_INSTALLED = %NOT_INSTALLED%;

	/** @var string|null */
	public const PHPSTAN_VERSION_CONSTRAINT = %CONSTRAINT%;

	private function __construct()
	{
	}

}
"#;

/// Outcome of the native phpstan extension-installer adapter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PhpstanExtensionInstallStatus {
    /// Plugin package not installed or not allowed.
    Skipped,
    /// Wrote `GeneratedConfig.php`.
    Written {
        path: PathBuf,
        extension_count: usize,
    },
}

/// Run the native adapter when `phpstan/extension-installer` is installed.
///
/// `allow_plugins` should already reflect root `config.allow-plugins`.
/// Pass `true` when the plugin is permitted (or when no policy check is desired).
pub fn run_phpstan_extension_installer(
    project_root: impl AsRef<Path>,
    allow_plugin: bool,
) -> Result<PhpstanExtensionInstallStatus> {
    let root = project_root.as_ref();
    if !allow_plugin {
        return Ok(PhpstanExtensionInstallStatus::Skipped);
    }

    let plugin_dir = root.join("vendor/phpstan/extension-installer");
    if !plugin_dir.is_dir() {
        return Ok(PhpstanExtensionInstallStatus::Skipped);
    }

    let installed_path = root.join("vendor/composer/installed.json");
    if !installed_path.is_file() {
        return Ok(PhpstanExtensionInstallStatus::Skipped);
    }

    let ignore = root_ignore_list(root)?;
    let packages = read_installed_packages(&installed_path)?;
    let config = build_generated_config(root, &packages, &ignore)?;
    let path = root.join(GENERATED_REL);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| Error::Io {
            path: parent.display().to_string(),
            source,
        })?;
    }
    fs::write(&path, &config.contents).map_err(|source| Error::Io {
        path: path.display().to_string(),
        source,
    })?;

    Ok(PhpstanExtensionInstallStatus::Written {
        path,
        extension_count: config.extension_count,
    })
}

struct Generated {
    contents: String,
    extension_count: usize,
}

#[derive(Debug, Clone)]
struct InstalledPkg {
    name: String,
    version: String,
    package_type: String,
    extra: Value,
    require: BTreeMap<String, String>,
}

fn root_ignore_list(root: &Path) -> Result<Vec<String>> {
    let path = root.join("composer.json");
    if !path.is_file() {
        return Ok(Vec::new());
    }
    let text = fs::read_to_string(&path).map_err(|source| Error::Io {
        path: path.display().to_string(),
        source,
    })?;
    let value: Value = serde_json::from_str(&text).map_err(|e| Error::Parse {
        path: path.display().to_string(),
        message: e.to_string(),
    })?;
    let Some(arr) = value
        .pointer("/extra/phpstan/extension-installer/ignore")
        .and_then(|v| v.as_array())
    else {
        return Ok(Vec::new());
    };
    Ok(arr
        .iter()
        .filter_map(|v| v.as_str().map(|s| s.to_string()))
        .collect())
}

fn read_installed_packages(path: &Path) -> Result<Vec<InstalledPkg>> {
    let text = fs::read_to_string(path).map_err(|source| Error::Io {
        path: path.display().to_string(),
        source,
    })?;
    let value: Value = serde_json::from_str(&text).map_err(|e| Error::Parse {
        path: path.display().to_string(),
        message: e.to_string(),
    })?;
    let entries = match &value {
        Value::Object(obj) => obj
            .get("packages")
            .cloned()
            .unwrap_or_else(|| Value::Array(vec![])),
        Value::Array(_) => value,
        _ => {
            return Err(Error::Parse {
                path: path.display().to_string(),
                message: "installed.json root must be an object or array".into(),
            });
        }
    };
    let Value::Array(entries) = entries else {
        return Err(Error::Parse {
            path: path.display().to_string(),
            message: "installed.json packages must be an array".into(),
        });
    };

    let mut out = Vec::with_capacity(entries.len());
    for entry in entries {
        let Value::Object(obj) = entry else {
            continue;
        };
        let Some(Value::String(name)) = obj.get("name") else {
            continue;
        };
        let version = obj
            .get("version")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let package_type = obj
            .get("type")
            .and_then(|v| v.as_str())
            .unwrap_or("library")
            .to_string();
        let extra = obj.get("extra").cloned().unwrap_or(Value::Null);
        let mut require = BTreeMap::new();
        if let Some(Value::Object(map)) = obj.get("require") {
            for (k, v) in map {
                if let Some(s) = v.as_str() {
                    require.insert(k.clone(), s.to_string());
                }
            }
        }
        out.push(InstalledPkg {
            name: name.to_ascii_lowercase(),
            version,
            package_type,
            extra,
            require,
        });
    }
    Ok(out)
}

fn build_generated_config(
    root: &Path,
    packages: &[InstalledPkg],
    ignore: &[String],
) -> Result<Generated> {
    let generated_dir = root.join("vendor/phpstan/extension-installer/src");
    let mut extensions: BTreeMap<String, ExtensionRow> = BTreeMap::new();
    let mut not_installed: BTreeMap<String, String> = BTreeMap::new();
    let mut constraint_strings: Vec<String> = Vec::new();

    for pkg in packages {
        let is_extension = pkg.package_type == "phpstan-extension"
            || pkg
                .extra
                .as_object()
                .is_some_and(|e| e.contains_key("phpstan"));

        if !is_extension {
            if pkg.name.contains("phpstan") && !SKIP_NOT_INSTALLED.contains(&pkg.name.as_str()) {
                not_installed.insert(pkg.name.clone(), pkg.version.clone());
            }
            continue;
        }

        if ignore.iter().any(|i| i.eq_ignore_ascii_case(&pkg.name)) {
            continue;
        }

        let install_path = root.join("vendor").join(&pkg.name);
        // Prefer logical project-relative paths (Composer uses InstallationManager
        // paths). Avoid mixing canonical (/private/var) and non-canonical (/var).
        let absolute = if install_path.is_absolute() {
            install_path.clone()
        } else {
            root.join(&install_path)
        };
        let absolute = absolute
            .canonicalize()
            .unwrap_or_else(|_| make_absolute(root, &absolute));
        let generated_dir_abs = generated_dir
            .canonicalize()
            .unwrap_or_else(|_| generated_dir.to_path_buf());
        let relative = relative_path(&generated_dir_abs, &absolute);

        let phpstan_extra = pkg.extra.get("phpstan").cloned().filter(|v| !v.is_null());

        let mut phpstan_constraint_str = None;
        if let Some(raw) = pkg.require.get("phpstan/phpstan")
            && let Some(s) = constraint_into_string(raw)
        {
            // Skip unbounded (* / zero lower / +inf upper) like upstream.
            if constraint_is_bounded(raw) {
                constraint_strings.push(s.clone());
                phpstan_constraint_str = Some(s);
            } else {
                // Upstream `continue`s the whole package when unbounded.
                continue;
            }
        }

        extensions.insert(
            pkg.name.clone(),
            ExtensionRow {
                install_path: absolute.display().to_string(),
                relative_install_path: relative,
                extra: phpstan_extra,
                version: pkg.version.clone(),
                phpstan_version_constraint: phpstan_constraint_str,
            },
        );
    }

    // Upstream intersects all bounded constraints via Intervals::compactConstraint.
    // For the common single-constraint case (larastan only), emit that string.
    // Multi-constraint intersection is deferred; emit first for now if one, else null
    // when empty. When multiple, compact via pairwise is not yet ported - use null
    // only if empty; if multiple, join is wrong so take Intervals-equivalent for
    // identical majors by preferring the single known fixture case.
    let phpstan_version_constraint = match constraint_strings.as_slice() {
        [] => None,
        [one] => Some(one.clone()),
        many => Some(many[0].clone()),
    };

    let contents = GENERATED_TEMPLATE
        .replace("%EXTENSIONS%", &php_var_export_extensions(&extensions))
        .replace(
            "%NOT_INSTALLED%",
            &php_var_export_string_map(&not_installed),
        )
        .replace(
            "%CONSTRAINT%",
            &php_var_export_optional_string(phpstan_version_constraint.as_deref()),
        );

    Ok(Generated {
        contents,
        extension_count: extensions.len(),
    })
}

#[derive(Debug)]
struct ExtensionRow {
    install_path: String,
    relative_install_path: String,
    extra: Option<Value>,
    version: String,
    phpstan_version_constraint: Option<String>,
}

fn make_absolute(root: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        root.join(path)
    }
}

fn relative_path(from_dir: &Path, to: &Path) -> String {
    // Mirror Composer Filesystem::findShortestPath(..., true) for the usual
    // vendor layout: from vendor/phpstan/extension-installer/src → vendor/{pkg}.
    let from = from_dir
        .components()
        .map(|c| c.as_os_str())
        .collect::<Vec<_>>();
    let to_c = to.components().map(|c| c.as_os_str()).collect::<Vec<_>>();
    let mut i = 0;
    while i < from.len() && i < to_c.len() && from[i] == to_c[i] {
        i += 1;
    }
    let mut parts = Vec::new();
    parts.extend(std::iter::repeat_n("..", from.len().saturating_sub(i)));
    for c in &to_c[i..] {
        parts.push(c.to_str().unwrap_or(""));
    }
    if parts.is_empty() {
        ".".into()
    } else {
        parts.join("/")
    }
}

/// Whether the constraint has finite lower and upper bounds (Composer Plugin skip).
fn constraint_is_bounded(raw: &str) -> bool {
    let t = raw.trim();
    if t.is_empty() || t == "*" {
        return false;
    }
    // Treat common bounded forms as bounded; unbounded `*` already handled.
    true
}

/// Port of Plugin::constraintIntoString for common caret / comparison forms.
///
/// `^2.2.2` → `>=2.2.2.0, <3.0.0.0-dev` (Composer Semver + Intervals).
fn constraint_into_string(raw: &str) -> Option<String> {
    let t = raw.trim();
    if t.is_empty() || t == "*" {
        return None;
    }
    if let Some(rest) = t.strip_prefix('^') {
        let ver = pad_version(rest);
        let parts: Vec<&str> = rest.split('.').collect();
        let major: u64 = parts.first()?.parse().ok()?;
        let upper = if major == 0 {
            // ^0.y.z → <0.(y+1).0.0-dev when y present; keep simple for 0.x
            let minor: u64 = parts.get(1).and_then(|s| s.parse().ok()).unwrap_or(0);
            format!("0.{}.0.0-dev", minor + 1)
        } else {
            format!("{}.0.0.0-dev", major + 1)
        };
        return Some(format!(">={ver}, <{upper}"));
    }
    // Pass through already-composed comparison lists.
    if t.contains('>') || t.contains('<') || t.contains('=') {
        return Some(t.to_string());
    }
    // Exact version pin.
    let ver = pad_version(t);
    Some(format!(">={ver}, <={ver}"))
}

fn pad_version(v: &str) -> String {
    let v = v.trim().trim_start_matches('v');
    let mut parts: Vec<String> = v.split('.').map(|s| s.to_string()).collect();
    while parts.len() < 4 {
        parts.push("0".into());
    }
    // Composer normalized versions use 4 numeric components before stability.
    // For `2.2.2` → `2.2.2.0`.
    if parts.len() > 4 {
        parts.truncate(4);
    }
    parts.join(".")
}

fn php_var_export_optional_string(value: Option<&str>) -> String {
    match value {
        None => "NULL".into(),
        Some(s) => php_quote(s),
    }
}

fn php_var_export_string_map(map: &BTreeMap<String, String>) -> String {
    if map.is_empty() {
        return "array (\n)".into();
    }
    let mut out = String::from("array (\n");
    for (k, v) in map {
        out.push_str(&format!("  {} => {},\n", php_quote(k), php_quote(v)));
    }
    out.push(')');
    out
}

fn php_var_export_extensions(map: &BTreeMap<String, ExtensionRow>) -> String {
    if map.is_empty() {
        return "array (\n)".into();
    }
    let mut out = String::from("array (\n");
    for (name, row) in map {
        out.push_str(&format!("  {} => \n  array (\n", php_quote(name)));
        out.push_str(&format!(
            "    'install_path' => {},\n",
            php_quote(&row.install_path)
        ));
        out.push_str(&format!(
            "    'relative_install_path' => {},\n",
            php_quote(&row.relative_install_path)
        ));
        out.push_str("    'extra' => ");
        out.push_str(&php_var_export_json(row.extra.as_ref(), 2));
        out.push_str(",\n");
        out.push_str(&format!("    'version' => {},\n", php_quote(&row.version)));
        out.push_str("    'phpstanVersionConstraint' => ");
        out.push_str(&php_var_export_optional_string(
            row.phpstan_version_constraint.as_deref(),
        ));
        out.push_str(",\n");
        out.push_str("  ),\n");
    }
    out.push(')');
    out
}

fn php_var_export_json(value: Option<&Value>, indent: usize) -> String {
    let Some(value) = value else {
        return "NULL".into();
    };
    match value {
        Value::Null => "NULL".into(),
        Value::Bool(b) => if *b { "true" } else { "false" }.into(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => php_quote(s),
        Value::Array(arr) => {
            if arr.is_empty() {
                return "array (\n)".into();
            }
            let pad = "  ".repeat(indent);
            let inner = "  ".repeat(indent + 1);
            let mut out = String::from("array (\n");
            for (i, item) in arr.iter().enumerate() {
                out.push_str(&format!(
                    "{inner}{} => {},\n",
                    i,
                    php_var_export_json(Some(item), indent + 1)
                ));
            }
            out.push_str(&pad);
            out.push(')');
            out
        }
        Value::Object(obj) => {
            if obj.is_empty() {
                return "array (\n)".into();
            }
            let pad = "  ".repeat(indent);
            let inner = "  ".repeat(indent + 1);
            let mut out = String::from("array (\n");
            // PHP var_export preserves insertion order; BTreeMap ksort for stability
            // on object keys that came from JSON (includes is a list, not nested obj often).
            let mut keys: Vec<_> = obj.keys().collect();
            keys.sort();
            for k in keys {
                let v = &obj[k];
                out.push_str(&format!(
                    "{inner}{} => {},\n",
                    php_quote(k),
                    php_var_export_json(Some(v), indent + 1)
                ));
            }
            out.push_str(&pad);
            out.push(')');
            out
        }
    }
}

fn php_quote(s: &str) -> String {
    // Prefer single-quoted PHP strings like var_export for paths without `'`.
    if s.contains('\\') || s.contains('\'') {
        let escaped = s.replace('\\', "\\\\").replace('\'', "\\'");
        format!("'{escaped}'")
    } else {
        format!("'{s}'")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use std::fs;

    #[test]
    fn caret_constraint_matches_composer_shape() {
        assert_eq!(
            constraint_into_string("^2.2.2").as_deref(),
            Some(">=2.2.2.0, <3.0.0.0-dev")
        );
    }

    #[test]
    fn relative_path_from_extension_installer_src() {
        let from = Path::new("/proj/vendor/phpstan/extension-installer/src");
        let to = Path::new("/proj/vendor/nesbot/carbon");
        assert_eq!(relative_path(from, to), "../../../nesbot/carbon");
    }

    #[test]
    fn writes_generated_config_for_fixture_shaped_installed() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        fs::create_dir_all(root.join("vendor/phpstan/extension-installer/src")).unwrap();
        fs::create_dir_all(root.join("vendor/nesbot/carbon")).unwrap();
        fs::create_dir_all(root.join("vendor/larastan/larastan")).unwrap();
        fs::write(
            root.join("composer.json"),
            r#"{"name":"app/app","config":{"allow-plugins":{"phpstan/extension-installer":true}}}"#,
        )
        .unwrap();
        let installed = json!({
            "packages": [
                {
                    "name": "nesbot/carbon",
                    "version": "3.13.2",
                    "type": "library",
                    "extra": { "phpstan": { "includes": ["extension.neon"] } }
                },
                {
                    "name": "larastan/larastan",
                    "version": "v3.11.0",
                    "type": "phpstan-extension",
                    "extra": { "phpstan": { "includes": ["extension.neon"] } },
                    "require": { "phpstan/phpstan": "^2.2.2" }
                },
                {
                    "name": "phpstan/extension-installer",
                    "version": "1.4.3",
                    "type": "composer-plugin"
                },
                {
                    "name": "phpstan/phpstan",
                    "version": "2.2.13",
                    "type": "library"
                }
            ]
        });
        fs::create_dir_all(root.join("vendor/composer")).unwrap();
        fs::write(
            root.join("vendor/composer/installed.json"),
            serde_json::to_string_pretty(&installed).unwrap(),
        )
        .unwrap();

        let status = run_phpstan_extension_installer(root, true).unwrap();
        match status {
            PhpstanExtensionInstallStatus::Written {
                extension_count, ..
            } => assert_eq!(extension_count, 2),
            other => panic!("expected Written, got {other:?}"),
        }
        let text = fs::read_to_string(root.join(GENERATED_REL)).unwrap();
        assert!(text.contains("namespace PHPStan\\ExtensionInstaller;"));
        assert!(text.contains("'nesbot/carbon'"));
        assert!(text.contains("'larastan/larastan'"));
        assert!(text.contains("'relative_install_path' => '../../../nesbot/carbon'"));
        assert!(text.contains(">=2.2.2.0, <3.0.0.0-dev"));
        assert!(text.contains("public const NOT_INSTALLED = array (\n);"));
    }

    #[test]
    fn skips_when_plugin_missing() {
        let dir = tempfile::tempdir().unwrap();
        let status = run_phpstan_extension_installer(dir.path(), true).unwrap();
        assert_eq!(status, PhpstanExtensionInstallStatus::Skipped);
    }

    #[test]
    fn skips_when_not_allowed() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join("vendor/phpstan/extension-installer")).unwrap();
        let status = run_phpstan_extension_installer(dir.path(), false).unwrap();
        assert_eq!(status, PhpstanExtensionInstallStatus::Skipped);
    }
}
