[package]
name = "puck_store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "puck: content-addressable store and vendor linking"

[dependencies]
thiserror.workspace = true
puck_dist.workspace = true
sha2.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile.workspace = true
puck_dist.workspace = true
zip = { workspace = true }
