//! Write `vendor/autoload.php` and `vendor/composer/*` autoload files.

use crate::classmap::build_classmap;
use crate::collect::{
    CollectedAutoloads, RelPath, prefix_lengths_psr4, prefixes_psr0,
};
use crate::php::{path_code, php_export_string, static_path_code};
use crate::platform_check::render_platform_check;
use crate::{Error, Result};
use puck_lock::LockFile;
use puck_manifest::Manifest;
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

const CLASS_LOADER: &str = include_str!("../vendor_composer/ClassLoader.php");
const INSTALLED_VERSIONS: &str = include_str!("../vendor_composer/InstalledVersions.php");
const LICENSE: &str = include_str!("../vendor_composer/LICENSE");

pub fn write_autoload_files(
    project_root: &Path,
    collected: &CollectedAutoloads,
    suffix: &str,
    authoritative: bool,
    lock: &LockFile,
    manifest: Option<&Manifest>,
    no_dev: bool,
) -> Result<()> {
    let vendor = project_root.join("vendor");
    let composer_dir = vendor.join("composer");
    fs::create_dir_all(&composer_dir).map_err(|source| Error::Io {
        path: composer_dir.display().to_string(),
        source,
    })?;

    write_file(&composer_dir.join("ClassLoader.php"), CLASS_LOADER)?;
    write_file(&composer_dir.join("InstalledVersions.php"), INSTALLED_VERSIONS)?;
    write_file(&composer_dir.join("LICENSE"), LICENSE)?;

    let psr4 = collected.psr4_sorted();
    let psr0 = collected.psr0_sorted();
    let has_files = !collected.files.is_empty();
    // Declared classmap scan after packages are linked under project_root.
    let classmap = build_classmap(project_root, &collected.classmap);

    write_file(
        &composer_dir.join("autoload_namespaces.php"),
        &map_file("autoload_namespaces.php", &psr0),
    )?;
    write_file(
        &composer_dir.join("autoload_psr4.php"),
        &map_file("autoload_psr4.php", &psr4),
    )?;
    write_file(
        &composer_dir.join("autoload_classmap.php"),
        &classmap_file(&classmap),
    )?;
    write_file(
        &composer_dir.join("autoload_files.php"),
        &files_file(&collected.files),
    )?;
    write_file(
        &composer_dir.join("autoload_static.php"),
        &static_file(suffix, collected, &psr4, &psr0, &classmap),
    )?;

    let platform_check = render_platform_check(lock, manifest, no_dev);
    let check_platform = platform_check.is_some();
    let platform_path = composer_dir.join("platform_check.php");
    if let Some(contents) = platform_check {
        write_file(&platform_path, &contents)?;
    } else if platform_path.exists() {
        fs::remove_file(&platform_path).map_err(|source| Error::Io {
            path: platform_path.display().to_string(),
            source,
        })?;
    }

    write_file(
        &composer_dir.join("autoload_real.php"),
        &real_file(suffix, has_files, authoritative, check_platform),
    )?;
    write_file(&vendor.join("autoload.php"), &autoload_php(suffix))?;

    Ok(())
}

fn write_file(path: &Path, contents: &str) -> Result<()> {
    fs::write(path, contents).map_err(|source| Error::Io {
        path: path.display().to_string(),
        source,
    })
}

const HEADER_VENDOR_BASE: &str = r#"<?php

// {name} @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
"#;

fn classmap_file(classmap: &BTreeMap<String, RelPath>) -> String {
    let mut out = HEADER_VENDOR_BASE.replace("{name}", "autoload_classmap.php");
    for (class, path) in classmap {
        out.push_str("    ");
        out.push_str(&php_export_string(class));
        out.push_str(" => ");
        out.push_str(&path_code(path));
        out.push_str(",\n");
    }
    out.push_str(");\n");
    out
}

fn map_file(name: &str, entries: &[(&str, &Vec<RelPath>)]) -> String {
    let mut out = HEADER_VENDOR_BASE.replace("{name}", name);
    for (ns, paths) in entries {
        let exported_paths: Vec<String> = paths.iter().map(|p| path_code(p)).collect();
        out.push_str("    ");
        out.push_str(&php_export_string(ns));
        out.push_str(" => array(");
        out.push_str(&exported_paths.join(", "));
        out.push_str("),\n");
    }
    out.push_str(");\n");
    out
}

fn files_file(files: &indexmap::IndexMap<String, RelPath>) -> String {
    let mut out = HEADER_VENDOR_BASE.replace("{name}", "autoload_files.php");
    for (id, path) in files {
        out.push_str("    ");
        out.push_str(&php_export_string(id));
        out.push_str(" => ");
        out.push_str(&path_code(path));
        out.push_str(",\n");
    }
    out.push_str(");\n");
    out
}

fn autoload_php(suffix: &str) -> String {
    format!(
        r#"<?php

// autoload.php @generated by Composer

if (PHP_VERSION_ID < 50600) {{
    if (!headers_sent()) {{
        header('HTTP/1.1 500 Internal Server Error');
    }}
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    if (!ini_get('display_errors')) {{
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {{
            fwrite(STDERR, $err);
        }} elseif (!headers_sent()) {{
            echo $err;
        }}
    }}
    throw new RuntimeException($err);
}}

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit{suffix}::getLoader();
"#
    )
}

fn real_file(suffix: &str, has_files: bool, authoritative: bool, check_platform: bool) -> String {
    let mut out = format!(
        r#"<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit{suffix}
{{
    private static $loader;

    public static function loadClassLoader($class)
    {{
        if ('Composer\Autoload\ClassLoader' === $class) {{
            require __DIR__ . '/ClassLoader.php';
        }}
    }}

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {{
        if (null !== self::$loader) {{
            return self::$loader;
        }}

"#
    );

    if check_platform {
        out.push_str("        require __DIR__ . '/platform_check.php';\n\n");
    }

    out.push_str(&format!(
        r#"        spl_autoload_register(array('ComposerAutoloaderInit{suffix}', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit{suffix}', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInit{suffix}::getInitializer($loader));

"#
    ));

    if authoritative {
        out.push_str("        $loader->setClassMapAuthoritative(true);\n\n");
    }

    out.push_str("        $loader->register(true);\n\n");

    if has_files {
        out.push_str(&format!(
            r#"        $filesToLoad = \Composer\Autoload\ComposerStaticInit{suffix}::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {{
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {{
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }}
        }}, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {{
            $requireFile($fileIdentifier, $file);
        }}

"#
        ));
    }

    out.push_str(
        r#"        return $loader;
    }
}
"#,
    );
    out
}

fn static_file(
    suffix: &str,
    collected: &CollectedAutoloads,
    psr4: &[(&str, &Vec<RelPath>)],
    psr0: &[(&str, &Vec<RelPath>)],
    classmap: &BTreeMap<String, RelPath>,
) -> String {
    let mut out = format!(
        r#"<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit{suffix}
{{
"#
    );

    let mut initializer = String::new();

    if !collected.files.is_empty() {
        out.push_str("    public static $files = array (\n");
        for (id, path) in &collected.files {
            out.push_str("        ");
            out.push_str(&php_export_string(id));
            out.push_str(" => ");
            out.push_str(&static_path_code(path));
            out.push_str(",\n");
        }
        out.push_str("    );\n\n");
    }

    if !psr4.is_empty() {
        let lengths = prefix_lengths_psr4(psr4);
        out.push_str("    public static $prefixLengthsPsr4 = array (\n");
        for (ch, group) in &lengths {
            out.push_str(&format!("        '{}' =>\n        array (\n", escape_char(*ch)));
            for (ns, len) in group {
                out.push_str("            ");
                out.push_str(&php_export_string(ns));
                out.push_str(&format!(" => {len},\n"));
            }
            out.push_str("        ),\n");
        }
        out.push_str("    );\n\n");

        out.push_str("    public static $prefixDirsPsr4 = array (\n");
        for (ns, paths) in psr4 {
            out.push_str("        ");
            out.push_str(&php_export_string(ns));
            out.push_str(" =>\n        array (\n");
            for (i, path) in paths.iter().enumerate() {
                out.push_str(&format!(
                    "            {i} => {},\n",
                    static_path_code(path)
                ));
            }
            out.push_str("        ),\n");
        }
        out.push_str("    );\n\n");

        initializer.push_str(&format!(
            "            $loader->prefixLengthsPsr4 = ComposerStaticInit{suffix}::$prefixLengthsPsr4;\n"
        ));
        initializer.push_str(&format!(
            "            $loader->prefixDirsPsr4 = ComposerStaticInit{suffix}::$prefixDirsPsr4;\n"
        ));
    }

    if !psr0.is_empty() {
        let grouped = prefixes_psr0(psr0);
        out.push_str("    public static $prefixesPsr0 = array (\n");
        for (ch, group) in &grouped {
            out.push_str(&format!("        '{}' =>\n        array (\n", escape_char(*ch)));
            for (ns, paths) in group {
                out.push_str("            ");
                out.push_str(&php_export_string(ns));
                out.push_str(" =>\n            array (\n");
                for (i, path) in paths.iter().enumerate() {
                    out.push_str(&format!(
                        "                {i} => {},\n",
                        static_path_code(path)
                    ));
                }
                out.push_str("            ),\n");
            }
            out.push_str("        ),\n");
        }
        out.push_str("    );\n\n");

        initializer.push_str(&format!(
            "            $loader->prefixesPsr0 = ComposerStaticInit{suffix}::$prefixesPsr0;\n"
        ));
    }

    // Declared classmap + InstalledVersions (Composer always emits $classMap).
    out.push_str("    public static $classMap = array (\n");
    for (class, path) in classmap {
        out.push_str("        ");
        out.push_str(&php_export_string(class));
        out.push_str(" => ");
        out.push_str(&static_path_code(path));
        out.push_str(",\n");
    }
    out.push_str("    );\n\n");
    initializer.push_str(&format!(
        "            $loader->classMap = ComposerStaticInit{suffix}::$classMap;\n"
    ));

    out.push_str(&format!(
        r#"    public static function getInitializer(ClassLoader $loader)
    {{
        return \Closure::bind(function () use ($loader) {{
{initializer}
        }}, null, ClassLoader::class);
    }}
}}
"#
    ));

    out
}

fn escape_char(ch: char) -> String {
    match ch {
        '\\' => "\\\\".to_owned(),
        '\'' => "\\'".to_owned(),
        c => c.to_string(),
    }
}
