//! Composer `platform_check.php` generation (php-only default).

use puck_lock::{LockFile, LockedPackage};
use puck_manifest::Manifest;
use puck_version::{ConstraintExpr, Operator, parse_constraints, php_version_compare};
use serde_json::Value;

/// Lower bound for a PHP version check.
#[derive(Debug, Clone, PartialEq, Eq)]
struct PhpLowerBound {
    /// Inclusive (`>=`) when true, exclusive (`>`) when false.
    inclusive: bool,
    /// Normalized Composer version string (e.g. `8.3.0.0-dev`).
    version: String,
}

/// Generate `platform_check.php` contents, or `None` when Composer would skip the file.
///
/// Matches Composer’s default `platform-check` = `php-only`: only the PHP version
/// (and php-64bit) lower bound across non-dev packages + root.
pub fn render_platform_check(
    lock: &LockFile,
    manifest: Option<&Manifest>,
    _no_dev: bool,
) -> Option<String> {
    let mut lowest: Option<PhpLowerBound> = None;
    let mut require_64bit = false;

    if let Some(manifest) = manifest {
        consider_require_map(
            manifest
                .require
                .iter()
                .map(|(k, v)| (k.as_str(), v.as_str())),
            &mut lowest,
            &mut require_64bit,
        );
    }

    for pkg in &lock.packages {
        consider_locked_package(pkg, &mut lowest, &mut require_64bit);
    }
    // Dev packages are never consulted: Composer skips them even when installed.

    if lowest.is_none() && !require_64bit {
        return None;
    }

    let mut php_check = String::new();
    if let Some(bound) = &lowest {
        let operator = if bound.inclusive { ">=" } else { ">" };
        let id = php_version_id(&bound.version);
        let human = php_version_human(&bound.version);
        php_check.push_str(&format!(
            "\nif (!(PHP_VERSION_ID {operator} {id})) {{\n    $issues[] = 'Your Composer dependencies require a PHP version \"{operator} {human}\". You are running ' . PHP_VERSION . '.';\n}}\n"
        ));
    }
    if require_64bit {
        php_check.push_str(
            "\nif (PHP_INT_SIZE !== 8) {\n    $issues[] = 'Your Composer dependencies require a 64-bit build of PHP.';\n}\n",
        );
    }

    Some(format!(
        r#"<?php

// platform_check.php @generated by Composer

$issues = array();
{php_check}
if ($issues) {{
    if (!headers_sent()) {{
        header('HTTP/1.1 500 Internal Server Error');
    }}
    if (!ini_get('display_errors')) {{
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {{
            fwrite(STDERR, 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . implode(PHP_EOL, $issues) . PHP_EOL.PHP_EOL);
        }} elseif (!headers_sent()) {{
            echo 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . str_replace('You are running '.PHP_VERSION.'.', '', implode(PHP_EOL, $issues)) . PHP_EOL.PHP_EOL;
        }}
    }}
    trigger_error(
        'Composer detected issues in your platform: ' . implode(' ', $issues),
        E_USER_ERROR
    );
}}
"#
    ))
}

fn consider_locked_package(
    pkg: &LockedPackage,
    lowest: &mut Option<PhpLowerBound>,
    require_64bit: &mut bool,
) {
    let Some(Value::Object(require)) = pkg.extra.get("require") else {
        return;
    };
    consider_require_map(
        require
            .iter()
            .filter_map(|(k, v)| v.as_str().map(|s| (k.as_str(), s))),
        lowest,
        require_64bit,
    );
}

fn consider_require_map<'a>(
    links: impl Iterator<Item = (&'a str, &'a str)>,
    lowest: &mut Option<PhpLowerBound>,
    require_64bit: &mut bool,
) {
    for (name, constraint) in links {
        let lower = name.to_ascii_lowercase();
        if lower == "php-64bit" {
            *require_64bit = true;
        }
        if (lower == "php" || lower == "php-64bit")
            && let Ok(expr) = parse_constraints(constraint)
            && let Some(bound) = extract_lower_bound(&expr)
        {
            raise_lower_bound(lowest, bound);
        }
    }
}

fn extract_lower_bound(expr: &ConstraintExpr) -> Option<PhpLowerBound> {
    let mut found: Option<PhpLowerBound> = None;
    walk_lower_bounds(expr, &mut found);
    found
}

fn walk_lower_bounds(expr: &ConstraintExpr, found: &mut Option<PhpLowerBound>) {
    match expr {
        ConstraintExpr::MatchAll => {}
        ConstraintExpr::Simple { operator, version } => match operator {
            Operator::Gte => raise_lower_bound(
                found,
                PhpLowerBound {
                    inclusive: true,
                    version: version.clone(),
                },
            ),
            Operator::Gt => raise_lower_bound(
                found,
                PhpLowerBound {
                    inclusive: false,
                    version: version.clone(),
                },
            ),
            Operator::Eq => raise_lower_bound(
                found,
                PhpLowerBound {
                    inclusive: true,
                    version: version.clone(),
                },
            ),
            _ => {}
        },
        ConstraintExpr::Multi {
            conjunctive,
            constraints,
        } => {
            if *conjunctive {
                for c in constraints {
                    walk_lower_bounds(c, found);
                }
            } else {
                // Disjunction: take the minimum lower bound among alternatives
                // (weakest). Composer’s Bound logic on MultiConstraint is more
                // nuanced; for php-only production checks, conjunctive ^ ranges
                // are the common case.
                let mut weakest: Option<PhpLowerBound> = None;
                for c in constraints {
                    let mut local = None;
                    walk_lower_bounds(c, &mut local);
                    if let Some(b) = local {
                        weaken_lower_bound(&mut weakest, b);
                    }
                }
                if let Some(b) = weakest {
                    raise_lower_bound(found, b);
                }
            }
        }
    }
}

fn raise_lower_bound(slot: &mut Option<PhpLowerBound>, candidate: PhpLowerBound) {
    match slot {
        None => *slot = Some(candidate),
        Some(current) => {
            if bound_cmp(&candidate, current) == std::cmp::Ordering::Greater {
                *slot = Some(candidate);
            }
        }
    }
}

fn weaken_lower_bound(slot: &mut Option<PhpLowerBound>, candidate: PhpLowerBound) {
    match slot {
        None => *slot = Some(candidate),
        Some(current) => {
            if bound_cmp(&candidate, current) == std::cmp::Ordering::Less {
                *slot = Some(candidate);
            }
        }
    }
}

fn bound_cmp(a: &PhpLowerBound, b: &PhpLowerBound) -> std::cmp::Ordering {
    match php_version_compare(&a.version, &b.version) {
        0 => match (a.inclusive, b.inclusive) {
            // exclusive (>) is a stronger lower bound than inclusive (>=) at equal version
            (false, true) => std::cmp::Ordering::Greater,
            (true, false) => std::cmp::Ordering::Less,
            _ => std::cmp::Ordering::Equal,
        },
        n if n < 0 => std::cmp::Ordering::Less,
        _ => std::cmp::Ordering::Greater,
    }
}

fn php_version_id(normalized: &str) -> u32 {
    let chunks = numeric_chunks(normalized);
    chunks[0].saturating_mul(10000) + chunks[1].saturating_mul(100) + chunks[2]
}

fn php_version_human(normalized: &str) -> String {
    let chunks = numeric_chunks(normalized);
    format!("{}.{}.{}", chunks[0], chunks[1], chunks[2])
}

fn numeric_chunks(normalized: &str) -> [u32; 3] {
    let base = normalized
        .split(['-', '+'])
        .next()
        .unwrap_or(normalized)
        .replace('-', ".");
    let mut parts = base.split('.').filter_map(|p| p.parse::<u32>().ok());
    [
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use puck_manifest::Manifest;
    use std::str::FromStr;

    #[test]
    fn laravel_style_php_83() {
        let lock = LockFile::from_str(
            r#"{
                "content-hash": "x",
                "packages": [{
                    "name": "laravel/framework",
                    "version": "v13.0.0",
                    "require": { "php": "^8.2" }
                }],
                "packages-dev": []
            }"#,
        )
        .expect("lock");
        let manifest = Manifest::from_value(serde_json::json!({
            "name": "laravel/laravel",
            "require": { "php": "^8.3", "laravel/framework": "^13.0" }
        }))
        .expect("manifest");
        let php = render_platform_check(&lock, Some(&manifest), true).expect("content");
        assert!(php.contains("platform_check.php @generated by Composer"));
        assert!(php.contains("PHP_VERSION_ID >= 80300"));
        assert!(php.contains("\">= 8.3.0\""));
        assert!(!php.contains("extension_loaded"));
    }

    #[test]
    fn none_when_no_php_requirement() {
        let lock = LockFile::from_str(
            r#"{"content-hash":"x","packages":[{"name":"acme/lib","version":"1.0.0"}],"packages-dev":[]}"#,
        )
        .expect("lock");
        assert!(render_platform_check(&lock, None, true).is_none());
    }
}
