# frozen_string_literal: true

# Generated by dist/homebrew/generate-formula.rb - do not edit by hand.
# brew tap VerburgtJimmy/puck https://github.com/VerburgtJimmy/puck
# brew install puck

class Puck < Formula
  desc "Native PHP package installer (Composer-compatible vendor/)"
  homepage "https://github.com/VerburgtJimmy/puck"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.1/puck-aarch64-apple-darwin.tar.gz"
      sha256 "998a6b111dcc235e1819c4b7bb09dd3d04c63380e20ddb7f9ac7d72d38f34ede"
    end
    on_intel do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.1/puck-x86_64-apple-darwin.tar.gz"
      sha256 "12c8cc1263790641f14743a7f4046093b8778de9a1c9b73ab8df2214499789d0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.1/puck-aarch64-unknown-linux-musl.tar.gz"
      sha256 "422080170f1b06fb7fd82328d4fc0b2c594953bf3a2909497fc728a9bef9d20c"
    end
    on_intel do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.1/puck-x86_64-unknown-linux-musl.tar.gz"
      sha256 "3f5c190d7de6e90a9c44890d50ee40d5759f85d1cf8074081c59f14646c77740"
    end
  end

  def install
    bin.install "puck"
  end

  test do
    assert_match(/puck/, shell_output("#{bin}/puck --help"))
  end
end
