# frozen_string_literal: true

# Generated by dist/homebrew/generate-formula.rb — do not edit by hand.
# brew tap VerburgtJimmy/puck https://github.com/VerburgtJimmy/puck
# brew install puck

class Puck < Formula
  desc "Native PHP package installer (Composer-compatible vendor/)"
  homepage "https://github.com/VerburgtJimmy/puck"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.2/puck-aarch64-apple-darwin.tar.gz"
      sha256 "c48f7c4d74c2465961b74a42b643ee4cf4ae2fed53cc9a742cf998910a0fd1a4"
    end
    on_intel do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.2/puck-x86_64-apple-darwin.tar.gz"
      sha256 "0ef235f4e5a6a1e5fd1e946921e97492fe1db5be752da51fd61a316cf89840ae"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.2/puck-aarch64-unknown-linux-musl.tar.gz"
      sha256 "2a85ce0468152ecdb38093bfff22750219db353e3b5dee9e283758700a490eb5"
    end
    on_intel do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.2/puck-x86_64-unknown-linux-musl.tar.gz"
      sha256 "9d6cec27babe06476fbaa63cad69ddc2893e3f9eff6cb76ff3077cd7c2ad78a8"
    end
  end

  def install
    bin.install "puck"
  end

  test do
    assert_match(/puck/, shell_output("#{bin}/puck --help"))
  end
end
