# frozen_string_literal: true

# Generated by dist/homebrew/generate-formula.rb — do not edit by hand.
# brew tap VerburgtJimmy/puck https://github.com/VerburgtJimmy/puck
# brew install puck

class Puck < Formula
  desc "Native PHP package installer (Composer-compatible vendor/)"
  homepage "https://github.com/VerburgtJimmy/puck"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.0/puck-aarch64-apple-darwin.tar.gz"
      sha256 "c992c9480355c92d1a1b1720bf1c764c04ffce75ba7963cc6f623c0002ce436d"
    end
    on_intel do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.0/puck-x86_64-apple-darwin.tar.gz"
      sha256 "5c71bb5315b816cf0beeda41186c3c1fb33d08aa4bef212f6a10790e698dbcb8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.0/puck-aarch64-unknown-linux-musl.tar.gz"
      sha256 "de4c7b146ad33fb1637271e243007b09115d68df7bd401b667831c4b0f067895"
    end
    on_intel do
      url "https://github.com/VerburgtJimmy/puck/releases/download/v0.1.0/puck-x86_64-unknown-linux-musl.tar.gz"
      sha256 "9559877e7639f618a628d7c693cc13d4ef9537fa55ac91b8f3d8399277d1b451"
    end
  end

  def install
    bin.install "puck"
  end

  test do
    assert_match(/puck/, shell_output("#{bin}/puck --help"))
  end
end
