//! Composer-compatible `vendor/bin` proxies.
//!
//! Mirrors Composer 2.x `BinaryInstaller::generateUnixyProxyCode` closely enough
//! that package scripts and `vendor/bin/*` invocations work.

use crate::{Error, Result};
use puck_lock::{LockFile, LockedPackage};
use regex::Regex;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::LazyLock;

static PHP_BIN_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?s)^(#!.*?\r?\n)?[\r\n\t ]*<\?php").expect("php bin regex"));

/// Write `vendor/bin` proxies for every package selected by the lock / `--no-dev`.
pub fn install_binaries(project_root: &Path, lock: &LockFile, no_dev: bool) -> Result<()> {
    let vendor = project_root.join("vendor");
    let bin_dir = vendor.join("bin");
    fs::create_dir_all(&bin_dir).map_err(|source| Error::Io {
        path: bin_dir.display().to_string(),
        source,
    })?;

    let packages: Vec<&LockedPackage> = if no_dev {
        lock.packages.iter().collect()
    } else {
        lock.packages
            .iter()
            .chain(lock.packages_dev.iter())
            .collect()
    };

    for pkg in packages {
        install_package_bins(&vendor, &bin_dir, pkg)?;
    }

    Ok(())
}

fn install_package_bins(vendor: &Path, bin_dir: &Path, pkg: &LockedPackage) -> Result<()> {
    let install_path = vendor_package_path(vendor, &pkg.name);
    for bin in pkg.bins() {
        let bin_rel = bin.trim_start_matches("./");
        if bin_rel.is_empty()
            || Path::new(bin_rel)
                .components()
                .any(|c| matches!(c, std::path::Component::ParentDir))
        {
            eprintln!("puck: skipped bin {bin} for {}: invalid path", pkg.name);
            continue;
        }
        let bin_path = install_path.join(bin_rel);
        if !bin_path.is_file() {
            eprintln!("puck: skipped bin {bin} for {}: file not found", pkg.name);
            continue;
        }

        let link = bin_dir.join(file_name(&bin_path));
        // Standard Composer layout: vendor/bin -> ../{vendor}/{pkg}/{bin}
        let relative = format!("../{}/{}", pkg.name, bin_rel.replace('\\', "/"));
        let code = generate_unixy_proxy(&bin_path, &relative, &pkg.name, vendor)?;
        write_executable(&link, &code)?;

        #[cfg(unix)]
        chmod_executable(&bin_path)?;
    }
    Ok(())
}

fn generate_unixy_proxy(
    bin_path: &Path,
    relative_from_bin: &str,
    package_name: &str,
    vendor: &Path,
) -> Result<String> {
    let peek = read_prefix(bin_path, 500)?;
    if PHP_BIN_RE.is_match(&peek) {
        return Ok(generate_php_proxy(
            bin_path,
            relative_from_bin,
            package_name,
            vendor,
            &peek,
        ));
    }
    Ok(generate_shell_proxy(relative_from_bin))
}

fn generate_php_proxy(
    bin_path: &Path,
    relative_from_bin: &str,
    package_name: &str,
    vendor: &Path,
    peek: &str,
) -> String {
    let shebang = match PHP_BIN_RE.captures(peek).and_then(|c| c.get(1)) {
        Some(m) => m.as_str().trim_end_matches(['\r', '\n']).to_owned(),
        None => "#!/usr/bin/env php".to_owned(),
    };

    let bin_path_exported = include_path_code(relative_from_bin);
    let autoload_exported = include_path_code("../autoload.php");

    let phpunit_path = vendor.join("phpunit/phpunit/phpunit");
    let is_phpunit = (package_name.eq_ignore_ascii_case("phpunit/phpunit")
        && file_name(bin_path) == "phpunit")
        || paths_equal(bin_path, &phpunit_path);

    let mut globals = String::from("$GLOBALS['_composer_bin_dir'] = __DIR__;\n");
    globals.push_str(&format!(
        "$GLOBALS['_composer_autoload_path'] = {autoload_exported};\n"
    ));

    let (opened_path_assign, phpunit_hack2, stream_hint) = if is_phpunit {
        globals.push_str(&format!(
            "$GLOBALS['__PHPUNIT_ISOLATION_EXCLUDE_LIST'] = $GLOBALS['__PHPUNIT_ISOLATION_BLACKLIST'] = array(realpath({bin_path_exported}));\n"
        ));
        (
            "                $opened_path = 'phpvfscomposer://'.$this->realpath;",
            "\n                    $data = str_replace('__DIR__', var_export(dirname($this->realpath), true), $data);\n                    $data = str_replace('__FILE__', var_export($this->realpath, true), $data);",
            " using a stream wrapper to prevent the shebang from being output on PHP<8 and\n * to replace the __FILE__ and __DIR__ constants in PHPUnit's files on PHP<8",
        )
    } else {
        (
            "                $opened_path = $this->realpath;",
            "",
            " using a stream wrapper to prevent the shebang from being output on PHP<8",
        )
    };

    format!(
        r##"{shebang}
<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path ({relative_from_bin})
 *{stream_hint}
 *
 * @generated
 */

namespace Composer;

{globals}
if (PHP_VERSION_ID < 80000) {{
    if (!class_exists('Composer\BinProxyWrapper')) {{
        /**
         * @internal
         */
        final class BinProxyWrapper
        {{
            private $handle;
            private $position;
            private $realpath;

            public function stream_open($path, $mode, $options, &$opened_path)
            {{
                // get rid of phpvfscomposer:// prefix for __FILE__ & __DIR__ resolution
                $opened_path = substr($path, 17);
                $this->realpath = realpath($opened_path) ?: $opened_path;
{opened_path_assign}
                $this->handle = fopen($this->realpath, $mode);
                $this->position = 0;

                return (bool) $this->handle;
            }}

            public function stream_read($count)
            {{
                $data = fread($this->handle, $count);

                if ($this->position === 0) {{
                    $data = preg_replace('{{^#!.*\r?\n}}', '', $data);
                }}{phpunit_hack2}

                $this->position += strlen($data);

                return $data;
            }}

            public function stream_cast($castAs)
            {{
                return $this->handle;
            }}

            public function stream_close()
            {{
                fclose($this->handle);
            }}

            public function stream_lock($operation)
            {{
                return $operation ? flock($this->handle, $operation) : true;
            }}

            public function stream_seek($offset, $whence)
            {{
                if (0 === fseek($this->handle, $offset, $whence)) {{
                    $this->position = ftell($this->handle);
                    return true;
                }}

                return false;
            }}

            public function stream_tell()
            {{
                return $this->position;
            }}

            public function stream_eof()
            {{
                return feof($this->handle);
            }}

            public function stream_stat()
            {{
                return array();
            }}

            public function stream_set_option($option, $arg1, $arg2)
            {{
                return true;
            }}

            public function url_stat($path, $flags)
            {{
                $path = substr($path, 17);
                if (file_exists($path)) {{
                    return stat($path);
                }}

                return false;
            }}
        }}
    }}

    if (
        (function_exists('stream_get_wrappers') && in_array('phpvfscomposer', stream_get_wrappers(), true))
        || (function_exists('stream_wrapper_register') && stream_wrapper_register('phpvfscomposer', 'Composer\BinProxyWrapper'))
    ) {{
        return include("phpvfscomposer://" . {bin_path_exported});
    }}
}}

return include {bin_path_exported};
"##
    )
}

fn generate_shell_proxy(relative_from_bin: &str) -> String {
    let normalized = relative_from_bin.replace('\\', "/");
    let bin_dir = Path::new(&normalized)
        .parent()
        .map(|p| p.to_string_lossy().into_owned())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| ".".into());
    let bin_file = Path::new(&normalized)
        .file_name()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| normalized.clone());

    let bin_dir_esc = shell_single_quote(&bin_dir);

    format!(
        r##"#!/usr/bin/env sh

# Support bash to support `source` with fallback on $0 if this does not run with bash
# https://stackoverflow.com/a/35006505/6512
selfArg="$BASH_SOURCE"
if [ -z "$selfArg" ]; then
    selfArg="$0"
fi

self=$(realpath "$selfArg" 2> /dev/null)
if [ -z "$self" ]; then
    self="$selfArg"
fi

dir=$(cd "${{self%[/\\]*}}" > /dev/null; cd {bin_dir_esc} && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

export COMPOSER_RUNTIME_BIN_DIR="$(cd "${{self%[/\\]*}}" > /dev/null; pwd)"

# If bash is sourcing this file, we have to source the target as well
bashSource="$BASH_SOURCE"
if [ -n "$bashSource" ]; then
    if [ "$bashSource" != "$0" ]; then
        source "${{dir}}/{bin_file}" "$@"
        return
    fi
fi

exec "${{dir}}/{bin_file}" "$@"
"##
    )
}

/// Composer `Filesystem::findShortestPathCode` style for `../…` targets from `vendor/bin`.
fn include_path_code(relative_from_bin: &str) -> String {
    let normalized = relative_from_bin.replace('\\', "/");
    if let Some(rest) = normalized.strip_prefix("../") {
        format!("__DIR__ . '/..'.'/{rest}'")
    } else if let Some(rest) = normalized.strip_prefix("./") {
        format!("__DIR__ . '/{rest}'")
    } else if normalized.starts_with('/') {
        format!("'{normalized}'")
    } else {
        format!("__DIR__ . '/{normalized}'")
    }
}

fn read_prefix(path: &Path, max: usize) -> Result<String> {
    let bytes = fs::read(path).map_err(|source| Error::Io {
        path: path.display().to_string(),
        source,
    })?;
    let end = max.min(bytes.len());
    Ok(String::from_utf8_lossy(&bytes[..end]).into_owned())
}

fn write_executable(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| Error::Io {
            path: parent.display().to_string(),
            source,
        })?;
    }
    let mut file = fs::File::create(path).map_err(|source| Error::Io {
        path: path.display().to_string(),
        source,
    })?;
    file.write_all(contents.as_bytes())
        .map_err(|source| Error::Io {
            path: path.display().to_string(),
            source,
        })?;
    #[cfg(unix)]
    chmod_executable(path)?;
    Ok(())
}

#[cfg(unix)]
fn chmod_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let meta = fs::metadata(path).map_err(|source| Error::Io {
        path: path.display().to_string(),
        source,
    })?;
    let mut perms = meta.permissions();
    // Composer uses 0777 & ~umask(); 0755 is the typical result and keeps scripts runnable.
    perms.set_mode(perms.mode() | 0o755);
    fs::set_permissions(path, perms).map_err(|source| Error::Io {
        path: path.display().to_string(),
        source,
    })?;
    Ok(())
}

fn vendor_package_path(vendor: &Path, name: &str) -> PathBuf {
    let mut path = vendor.to_path_buf();
    for part in name.split('/') {
        path.push(part);
    }
    path
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_default()
}

fn paths_equal(a: &Path, b: &Path) -> bool {
    a.to_string_lossy().replace('\\', "/") == b.to_string_lossy().replace('\\', "/")
}

fn shell_single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn include_path_code_matches_composer_style() {
        assert_eq!(
            include_path_code("../psy/psysh/bin/psysh"),
            "__DIR__ . '/..'.'/psy/psysh/bin/psysh'"
        );
        assert_eq!(
            include_path_code("../autoload.php"),
            "__DIR__ . '/..'.'/autoload.php'"
        );
    }

    #[test]
    fn php_bin_regex_detects_shebang_php() {
        assert!(PHP_BIN_RE.is_match("#!/usr/bin/env php\n<?php\n"));
        assert!(PHP_BIN_RE.is_match("<?php\n"));
        assert!(!PHP_BIN_RE.is_match("#!/usr/bin/env sh\necho hi\n"));
    }

    #[test]
    fn php_proxy_mentions_target_and_globals() {
        let code = generate_php_proxy(
            Path::new("/tmp/vendor/psy/psysh/bin/psysh"),
            "../psy/psysh/bin/psysh",
            "psy/psysh",
            Path::new("/tmp/vendor"),
            "#!/usr/bin/env php\n<?php\n",
        );
        assert!(code.starts_with("#!/usr/bin/env php\n"));
        assert!(code.contains("$GLOBALS['_composer_bin_dir'] = __DIR__;"));
        assert!(code.contains("__DIR__ . '/..'.'/psy/psysh/bin/psysh'"));
        assert!(code.contains("phpvfscomposer://"));
        assert!(!code.contains("__PHPUNIT_ISOLATION"));
    }

    #[test]
    fn phpunit_proxy_includes_isolation_hacks() {
        let code = generate_php_proxy(
            Path::new("/tmp/vendor/phpunit/phpunit/phpunit"),
            "../phpunit/phpunit/phpunit",
            "phpunit/phpunit",
            Path::new("/tmp/vendor"),
            "#!/usr/bin/env php\n<?php\n",
        );
        assert!(code.contains("__PHPUNIT_ISOLATION_EXCLUDE_LIST"));
        assert!(code.contains("phpvfscomposer://'.$this->realpath"));
    }
}
