[package]
name = "puck_install"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "puck: install planner and executor"

[dependencies]
indexmap.workspace = true
puck_dist.workspace = true
puck_lock.workspace = true
puck_manifest.workspace = true
puck_store.workspace = true
puck_version.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
