[package]
name = "puck_autoload"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "puck: Composer-compatible autoload generation"

[dependencies]
indexmap.workspace = true
md-5.workspace = true
puck_lock.workspace = true
puck_manifest.workspace = true
puck_version.workspace = true
regex.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
